import time
import requests
import unittest

import metrics


class TestMetricsHTTP(unittest.TestCase):
    def setUp(self) -> None:
        metrics._counters.clear()

    def test_labeled_rpc_counters_and_endpoint(self):
        # increment labeled counter
        metrics.inc_exchange_rpc_retry('SportsAPING/v1.0/placeOrders')
        # generic counter should be incremented
        self.assertEqual(metrics.get_counters().get('exchange_rpc_retries'), 1)
        # method-specific counter should be present
        method_name = 'exchange_rpc_retries_SportsAPING_v1_0_placeOrders'
        self.assertEqual(metrics.get_counters().get(method_name), 1)

        # Start HTTP server on ephemeral port
        server = metrics.MetricsServer(port=0)
        server.start()
        try:
            # Give server a moment
            time.sleep(0.05)
            # server.host may be 0.0.0.0 (not connectable); prefer localhost
            host = '127.0.0.1'
            port = server._server.server_address[1]
            r = requests.get(f'http://{host}:{port}/metrics', timeout=2)
            self.assertEqual(r.status_code, 200)
            text = r.text
            # Ensure Prometheus-style HELP/TYPE lines exist
            self.assertIn('# HELP exchange_rpc_retries autogenerated', text)
            self.assertIn('# TYPE exchange_rpc_retries counter', text)
            # Ensure method-specific metric appears
            self.assertIn(method_name + ' 1', text)
        finally:
            server.stop()

    def test_get_metrics_text_format(self):
        metrics._counters.clear()
        metrics.inc_bet_placed()
        txt = metrics.get_metrics_text()
        self.assertIn('# HELP bets_placed autogenerated', txt)
        self.assertIn('# TYPE bets_placed counter', txt)
        self.assertIn('bets_placed 1', txt)
